version: '3.8'
services:
  stats-server:
    build: stats/server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorewithme
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    image: amazoncorretto:11-alpine-jdk
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
